### ISSUE TITLE
relative import in scss?

### ISSUE THREAD

**Issue by wojtkowiak** [nathantreid/meteor-css-modules#20]
For me is not entirely clear in the docs. Is this valid?
`composes: b from "../../b.mss";`
or `composes: b from "/b.mss";`
or `composes: b from "./../../b.mss";`
The last one works but is giving some issues.

**Comment by akanix42** [comment]
All three of those should be working, but I'm currently receiving some errors:
`CSS Modules: unable to read file /b.mss` and
`packages/mss/css-modules-build-plugin.js:226:10: Cannot read property 'length' of undefined`.
Is that what you are seeing as well?

**Comment by akanix42** [comment]
This should be resolved in version 1.1.1. Are you still experiencing issues?

**Comment by wojtkowiak** [comment]
Sorry I did not respond sooner. Seems that it works pretty well now, thanks :+1:
One question by the way. Is composes in any way different from using @import / @extends from scss?

**Comment by akanix42** [comment]
yeah, it's a little different. @extend copies the styles, whereas composes combines the classes. So given

``` css
.a {
 color: red;
}

.b {
 font-size: 14px;
}
```

if you do 

``` css
.b { 
  composes: a;
}
```

then the result of `<someTag class="{{styles.b}}">` is `<someTag class="b a">`.

If you do an extend, the properties are copied in, so the result is just `<someTag class="b">`.
The primary difference is that if you have

``` css
.a {
 color: red;
}

.b {
 composes: a;
 font-size: 14px;
 color: purple;
}
```

The color won't necessarily be purple since both classes are applied. If you use extend the class instead, you will know for sure which style will be applied.
