### ISSUE TITLE
Unknown word during start up

### ISSUE THREAD

**Issue by pricetula** [nathantreid/meteor-css-modules#76]
Errors emmited during startup of meteor app

   Processing files with nathantreid:css...  /
/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Processing Step: CSS Modules / PostCSS compilation
Unable to compile /home/pricetula/METEOR/startupconnect/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css
CssSyntaxError: /home/pricetula/METEOR/startupconnect/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css:14:1: Unknown word

//# sourceMappingURL=map-file-comment.css.map
^
/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> Errors prevented startup:                  

   While processing files with nathantreid:css-modules (for target web.browser):
   error: /home/pricetula/METEOR/startupconnect/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css:14:1: Unknown
   word

**Comment by akanix42** [comment]
I messed up the publish of 2.3.0. Please give nathantreid:css-modules@2.3.1 a try. Thanks!
If that doesn't work, you'll want to add an [ignorePaths setting](https://github.com/nathantreid/meteor-css-modules/wiki/Package-Options) to avoid processing the `node_modules/convert-source-map/test` directory.

**Comment by yanickrochon** [comment]
Doesn't work for me.

```
=> Errors prevented startup:

   While processing files with nathantreid:css-modules (for target web.browser):
   error: /path/to/app/node_modules/convert-source-map/test/fixtures/map-file-comment-double-slash.css:14:1: Unknown word

=> Your application has errors. Waiting for file change.
```

## Edit

Here is the faulty CSS

```css
.header {
  background: #444;
  border: solid;
  padding: 10px;
  border-radius: 10px 5px 10px 5px;
  color: #b4b472; }

#main li {
  color: green;
  margin: 10px;
  padding: 10px;
  font-size: 18px; }

//# sourceMappingURL=map-file-comment.css.map
```

(**Note**: the last line is the one at fault. Not sure why they wrote that one there.)
